services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  worker:
    build: .
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: "redis://redis:6379/0"
      DATABASE_URL: "postgres://postgres:password@db:5432/postgres"
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  db_data:

