global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'devops-simple-worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:8000']   

